name: docs

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build_docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install Poetry
      run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
    - name: Add Poetry to PATH
      run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: poetry install
    - name: Generate schema docs
      run: poetry run af doc-schema schema/attack-flow-2022-01-05-draft.json docs/standard.rst
    - name: Build HTML docs
      run: poetry run sphinx-build -M html d docs/_build -W --keep-going
    - name: Upload HTML docs
      uses: actions/upload-artifact@v3
      with:
        name: attack_flow_docs_html
        path: docs/_build/html/
    - name: Install TeX Live
      run: sudo apt install -y latexmk texlive texlive-latex-extra
    - name: Build PDF docs
      run: poetry run sphinx-build -M latexpdf docs docs/_build
    - name: Upload PDF docs
      uses: actions/upload-artifact@v3
      with:
        name: attack_flow_docs_pdf
        path: docs/_build/latex/attackflow.pdf
