name: test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install Poetry
      run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
    - name: Add Poetry to PATH
      run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH
    - name: Install Dependencies
      run: poetry install
    - name: Test and lint with pytest
      run: poetry run make test-ci
    - name: Validate Corpus
      run: poetry run make validate
    - name: Upload Coverage to CodeCov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_SECRET }}
        files: coverage.xml
        verbose: true
    - name: Bandit Security Check
      run: |
        poetry run bandit -r src/ -ll -ii
    - name: Safety Vulnerability Check
      run: |
        poetry export -f requirements.txt | poetry run safety check --stdin
