name: test

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install Poetry
      run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
    - name: Install Dependencies
      run: poetry install
    - name: Test and lint with pytest
      run: poetry run pytest --cov=src/ --cov-report=xml --flake8
    - name: Validate Corpus
      env:
        PYTHONPATH: src/
      run: |
        poetry run python -m attack_flow.scripts.validate_doc \
          schema/attack-flow-2022-01-05-draft.json \
          schema/attack-flow-example.json \
          corpus/*.json
    - name: Upload Coverage to CodeCov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_SECRET }}
        files: coverage.xml
        verbose: true
    - name: Bandit Security Check
      run: |
        poetry run bandit -r src/ -ll -ii
    - name: Safety Vulnerability Check
      run: |
        poetry run safety check --file requirements/requirements.txt
